[[ $- != *i* ]] && return
[[ -t 0 ]] && stty stop undef
set -o vi
eval "$(fzf --bash)"

if [[ "$PROMPT_COMMAND" == *"__vsc_prompt_cmd_original"* ]] && \
   ! declare -F __vsc_prompt_cmd_original >/dev/null; then
    PROMPT_COMMAND="${PROMPT_COMMAND/__vsc_prompt_cmd_original; /}"
    PROMPT_COMMAND="${PROMPT_COMMAND/__vsc_prompt_cmd_original/}"
fi

add_plugin() {
    local repo_path="$1"
    local base_dir="$HOME/.local/share/bash"
    local plugin_dir="$base_dir/${repo_path##*/}"

    if [[ ! -d "$plugin_dir" ]]; then
        mkdir -p "$base_dir"
        git clone "https://github.com/$repo_path" "$plugin_dir"
    fi

    if [[ -f "$plugin_dir/${repo_path##*/}.sh" ]]; then
        source "$plugin_dir/${repo_path##*/}.sh"
    fi

    if [[ -d "$plugin_dir/bash" ]]; then
        for f in "$plugin_dir/bash/"*.sh; do
            [[ -f "$f" ]] && source "$f"
        done
    fi
}

add_plugin lincheney/fzf-tab-completion

export PATH="$(find ~/.local/bin/nvim/bin -type d -printf '%p:'):$(find ~/.local/bin -type d -printf '%p:'):$PATH"
export PATH="${PATH%:}"

PS1='\[\e[1;34m\]TT $IRD_ARCH_NAME | \[\e[0;32m\]\W\[\e[0m\] > '

HISTFILE="$XDG_DATA_HOME/bash/history"
HISTSIZE=1000000
HISTFILESIZE=1000000
shopt -s histappend

export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

export TERM=tmux-256color
export EDITOR=nvim

export MANPAGER='nvim +Man!'

export PYTHON_HISTORY="$XDG_STATE_HOME/python/history"

export TTY="$(tty)"

export LC_ALL=C.UTF-8
export LANG=C.UTF-8

export FZF_DEFAULT_COMMAND="rg --files --hidden"
export FZF_DEFAULT_OPTS="--ansi --color=16 --style full:sharp --info inline-right --layout=reverse --height=40%"
export FZF_COMPLETION_OPTS=""
export FZF_ALT_C_COMMAND="fd -t d -H --exclude '.git' --exclude '.gitignore' --exclude '.var' --exclude '.cache' --exclude '.ssh'"
export FZF_ALT_C_OPTS="--preview 'ls -A --group-directories-first --color=always {}/ 2>/dev/null; cat {} 2>/dev/null'"

alias ls="LC_COLLATE=C ls -A --group-directories-first --color=auto"
alias ll="ls -oh"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias cp="cp -rfv"
alias mv="mv -fv"
alias rm="rm -rfv"
alias mkdir="mkdir -pv"

binds=(
  	'\ef:yazi'
	'\ev:nvim'
	'\t:fzf_bash_completion'
)

for b in "${binds[@]}"; do
	IFS=: read -r key cmd <<< "$b"
	bind -x "\"$key\":$cmd < \$TTY"
done

bind -m vi-command '"\C-@": "\C-z\ec\C-z"'
bind -m vi-insert '"\C-@": "\C-z\ec\C-z"'
bind -r '\ec'
bind -m vi-insert '"\C-l": clear-screen'
bind -m vi-command '"\C-l": clear-screen'
bind -m vi-insert '"\C-e": vi-movement-mode'
bind -m vi-insert '"\e": ""'

stty sane

# Ensure proper initialization in tmux
if [[ -z "$TMUX" ]] && [[ "$TERM" != "tmux-256color" ]]; then
    export SHELL=/bin/bash
fi

